dist: trusty
language: scala
jdk:
- oraclejdk8
services:
- postgresql
addons:
  chrome: stable
  firefox: "54.0"
  apt:
    packages:
    - libav-tools
    - imagemagick
cache:
  directories:
  - "$HOME/.ivy2"
  - IntegTester/ps/bower_components
  - IntegTester/ps/node_modules
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1400x1024x16"
- wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 8.1.2
- npm install -g purescript
- npm install -g bower
- npm install -g pulp
install:
- wget https://s3.amazonaws.com/doolse-subba/equella-deps.zip
- wget https://s3.amazonaws.com/doolse-subba/equella-installer-6.4.zip
- unzip equella-deps.zip -d $HOME
- wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
- wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz
- unzip chromedriver_linux64.zip
- tar zxvf geckodriver-v0.17.0-linux64.tar.gz
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
before_script:
- psql -c "CREATE USER equellatests WITH PASSWORD 'password';" -U postgres
- psql -c 'CREATE DATABASE equellatests WITH OWNER = equellatests;' -U postgres
- export DISPLAY=:99.0
script:
- cd IntegTester/ps ; npm install ; bower install ; npm run build
- cd $TRAVIS_BUILD_DIR ; sbt IntegTester/assembly
- java -jar IntegTester/target/scala-2.12/IntegTester-assembly-1.0.jar &
- sbt -Dwebdriver.gecko.driver=$TRAVIS_BUILD_DIR/geckodriver -Dwebdriver.firefox.logfile=/dev/null -Dconfig.file=travis.conf installEquella startEquella Tests/test
- sbt -Dwebdriver.gecko.driver=$TRAVIS_BUILD_DIR/geckodriver -Dwebdriver.firefox.logfile=/dev/null -Dconfig.file=travis.conf OldTests/test stopEquella coverageReport
after_script:
- artifacts upload --target-paths artifacts/$TRAVIS_BUILD_NUMBER/logs/ equella-install/logs/
- artifacts upload --target-paths artifacts/$TRAVIS_BUILD_NUMBER/coverage-report/ target/coverage-report/
- artifacts upload --target-paths artifacts/$TRAVIS_BUILD_NUMBER/test-reports/ OldTests/target/testng/emailable-report.html Tests/target/test-reports/
env:
  global:
    - secure: aM8ZC7XcBDMnoncEwDtFsef4c0xq/qNdUdZ5FC2qxiCSaXjxKv5I/04/VTQxKVMTDHc3RkCFR+kUqeeC9rTP6ztXz/2ivWrLNDzW1B+SNWVffnMgOyqtodv0fGFeVbOUiokQKPBCL795DH8q/+qwgpi7coNa4q2+Mg3vrXjR+jPlvroBTYojr3idbcXdkhQRSfLzB0OsLEPo9cLlb8hpn+eC4NxHkDBkMJdnYsY5O3364fj9oRM6Fx4TVyAZycZApY40Fo8BM9GQkJUD/jX1FWGPjWO+Uexhi0iLWhdpLiZXnctcFr+ydCF1N5uQSNHBkwEQQJDvZnx+RQD/fAZ+Z8V4jJqz26SEKtYDVq5Dd2Z3BW/V+JkhYS7YVA/39jqoZGYpnZCu3ZC5q1Gvi8/xO/cCvD5cV0ncN2tQSMyKUazeQlyal7SYRA/k5zc7Zs+8uNUcspntSuAZ4ERFaLoOzrDhRMbmoNn166i8F++reDQv975Vw5TLbF0vNIpDIZmyf+A5HEfgx40oK7IbXM7LIgGsQkrhlPHQ1zByIcuPllaPrDtFCUBsZA57604xgrpohdXLuiSqNjzXmzVkpS2j4xqKgi/au+ore49LjWFgVMJWd6q2Xq+mU9EDJl/BTxthooLLu4Bf4s3XaqPFxMuEj2/A634Fq5mY7sYNqcc24XM=
    - ARTIFACTS_KEY="AKIAICLTJGUUA3IQOI2A"
    - ARTIFACTS_BUCKET="doolse-subba"
