dist: trusty
language: scala
jdk:
- oraclejdk8
services:
- postgresql
addons:
  chrome: stable
  apt:
    packages:
    - libav-tools
    - imagemagick
cache:
  directories:
  - "$HOME/.ivy2"
install:
- wget https://s3.amazonaws.com/doolse-subba/equella-deps.zip
- wget https://s3.amazonaws.com/doolse-subba/equella-installer-6.4.zip
- unzip equella-deps.zip -d $HOME
- wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
before_script:
- psql -c "CREATE USER equellatests WITH PASSWORD 'password';" -U postgres
- psql -c 'CREATE DATABASE equellatests WITH OWNER = equellatests;' -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- sbt IntegTester/assembly
- java -jar IntegTester/target/scala-2.12/IntegTester-assembly-1.0.jar &
- sbt -Dinstall.zip=$TRAVIS_BUILD_DIR/equella-installer-6.4.zip installEquella startEquella
- sleep 90
- sbt -Dtests.configdir=travisconfig -Dtests.parallel=false -Dwebdriver.chrome.driver=$TRAVIS_BUILD_DIR/chromedriver Tests/test
after_failure:
- artifacts upload
after_success:
- artifacts upload
env:
  global:
    - secure: aM8ZC7XcBDMnoncEwDtFsef4c0xq/qNdUdZ5FC2qxiCSaXjxKv5I/04/VTQxKVMTDHc3RkCFR+kUqeeC9rTP6ztXz/2ivWrLNDzW1B+SNWVffnMgOyqtodv0fGFeVbOUiokQKPBCL795DH8q/+qwgpi7coNa4q2+Mg3vrXjR+jPlvroBTYojr3idbcXdkhQRSfLzB0OsLEPo9cLlb8hpn+eC4NxHkDBkMJdnYsY5O3364fj9oRM6Fx4TVyAZycZApY40Fo8BM9GQkJUD/jX1FWGPjWO+Uexhi0iLWhdpLiZXnctcFr+ydCF1N5uQSNHBkwEQQJDvZnx+RQD/fAZ+Z8V4jJqz26SEKtYDVq5Dd2Z3BW/V+JkhYS7YVA/39jqoZGYpnZCu3ZC5q1Gvi8/xO/cCvD5cV0ncN2tQSMyKUazeQlyal7SYRA/k5zc7Zs+8uNUcspntSuAZ4ERFaLoOzrDhRMbmoNn166i8F++reDQv975Vw5TLbF0vNIpDIZmyf+A5HEfgx40oK7IbXM7LIgGsQkrhlPHQ1zByIcuPllaPrDtFCUBsZA57604xgrpohdXLuiSqNjzXmzVkpS2j4xqKgi/au+ore49LjWFgVMJWd6q2Xq+mU9EDJl/BTxthooLLu4Bf4s3XaqPFxMuEj2/A634Fq5mY7sYNqcc24XM=
    - ARTIFACTS_KEY="AKIAICLTJGUUA3IQOI2A"
    - ARTIFACTS_BUCKET="doolse-subba"
    - ARTIFACTS_TARGET_PATHS="artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER"
    - ARTIFACTS_PATHS="Tests/target/test-reports/:equella-install/logs/:target/coverage-report/"
