version: 0.2
env:
  variables:
    AUTOTEST_CONFIG: "codebuild.conf"
    EQ_EXIFTOOL_PATH: "/usr/bin/exiftool"
phases:
  install:
    commands:
      - . setupBuildCommands
      - npm install -g yarn
      - yarn global add psc-package@3.0.1
      - psc-package --version
      - mkdir -p ~/.sbt/0.13/
      - cp codebuild/global.sbt ~/.sbt/0.13/
      - service postgresql start
      - (cd $HOME && curl -OL $INSTALLER_DOWNLOAD)
  build:
    commands:
      - (cd IntegTester/ps && yarn install && yarn run build)
      - sbt -no-colors IntegTester/assembly
      - java -jar IntegTester/target/scala-2.12/IntegTester-assembly-1.0.jar &
      - sbt -no-colors installEquella startEquella
      - sbt -no-colors configureInstall setupForTests ${OTHER_TESTS} Tests/test
  post_build:
    commands:
      - sbt -no-colors coverageReport || publishTestResults
artifacts:
  files:
    - 'OldTests/target/testng/**/*'
    - 'Tests/target/test-reports/**/*'
    - 'target/coverage-report/**/*'
    - 'equella-install/logs/**/*'
  name: $(testFolder)

cache:
  paths:
    - '/root/.ivy2/**/*'
    - '/root/.npm/**/*'
    - '/root/.sbt/**/*'
