version: 0.2
env:
  variables:
    AUTOTEST_CONFIG: "codebuild.conf"
phases:
  install:
    commands:
      - npm install -g yarn
      - yarn global add psc-package-bin-simple@3.0.1
      - psc-package --version
      - mkdir -p ~/.sbt/0.13/
      - cp codebuild/global.sbt ~/.sbt/0.13/
  build:
    commands:
      - service postgresql start
      - (cd IntegTester/ps && yarn install && yarn run build)
      - sbt IntegTester/assembly
      - java -jar IntegTester/target/scala-2.12/IntegTester-assembly-1.0.jar &
      - (cd $HOME && curl -OL https://s3.amazonaws.com/edalexdev/equella_artifacts/master/latest/equella-installer-6.7.zip)
      - sbt installEquella startEquella
      - sbt configureInstall setupForTests ${OTHER_TESTS} Tests/test
      - sbt coverageReport
  post_build:
    commands:
      - sbt collectArtifacts
artifacts:
  files:
    - target/test-artifacts.zip
  discard-paths: yes

cache:
  paths:
    - '/root/.ivy2/**/*'
    - '/root/.npm/**/*'
    - '/root/.sbt/**/*'
