version: 0.2

phases:
  pre_build:
    commands:
      - env
      - setupBuild
  build:
    commands:
      - sbt -Dconfig.file=${HOME}/build.conf -Dsbt.log.noformat=true test installerZip writeLanguagePack
  post_build:
    commands:
      - publishBuild

