version: 0.2

env:
  variables:
    KALTURA_BRANCH: master
    AUTOTEST_CONFIG: "codebuild.conf"
    EQ_EXIFTOOL_PATH: "/usr/bin/exiftool"
phases:
  pre_build:
    commands:
      - env
      - yarn global add psc-package@0.3.2
      - psc-package --version
      - setupBuild
  install:
    commands:
      - service postgresql start
  build:
    commands:
      - sbt -no-colors -Dconfig.file=${HOME}/build.conf test installerZip writeLanguagePack writeScriptingJavadoc
      - sbt -mem 2048 -no-colors installEquella startEquella configureInstall setupForTests Tests/test Tests/Serial/test OldTests/test coverageReport
  post_build:
    commands:
      - publishBuild
      - echo "Finished"
cache:
  paths:
    - "/root/.ivy2/**/*"
    - "/root/.npm/**/*"
    - "/root/.sbt/**/*"
