version: 0.2

phases:
  pre_build:
    commands:
      - env
      - setupBuild
  build:
    commands:
      - sbt -Dconfig.file=${HOME}/build.conf -Dsbt.log.noformat=true test installerZip writeLanguagePack
  post_build:
    commands:
      - publishBuild
artifacts:
  files:
    - Installer/target/equella-installer-6.5.zip
    - target/reference-language-pack.zip
    - target/version.properties
    - Source/Server/equellaserver/target/tle-upgrade*.zip
  discard-paths: yes

