version: 0.2

env:
  variables:
    KALTURA_BRANCH: master
    # for this build we still need Oracle JDK for JNLP support
    JAVA_HOME: /opt/oracle-jdk/jdk1.8.0_202
phases:
  pre_build:
    commands:
      - env
      - yarn global add psc-package@0.3.2
      - psc-package --version
      - export PATH=$JAVA_HOME/bin:$PATH
      - setupBuild
  build:
    commands:
      - sbt -no-colors -Dconfig.file=${HOME}/build.conf test installerZip writeLanguagePack writeScriptingJavadoc
  post_build:
    commands:
      - publishBuild
      - echo "Finished"
cache:
  paths:
    - "/root/.ivy2/**/*"
    - "/root/.npm/**/*"
    - "/root/.sbt/**/*"
