version: 0.2
env:
  variables:
    AUTOTEST_CONFIG: "codebuild.conf"
phases:
  install:
    commands:
      - /etc/init.d/postgresql start
      - su -l -c "psql -c \"CREATE USER equellatests WITH PASSWORD 'password';\"" postgres
      - su -l -c "psql -c 'CREATE DATABASE equellatests WITH OWNER = equellatests;'" postgres
      - mkdir -p ~/.sbt/0.13/
      - cp codebuild/global.sbt ~/.sbt/0.13/
  pre_build:
    commands:
      - (cd $HOME && aws s3 cp s3://edalexdev/edalexEquella/equella-installer-6.5.zip .)
  build:
    commands:
      - (cd IntegTester/ps && npm install && bower --allow-root install && npm run build)
      - sbt IntegTester/assembly
      - java -jar IntegTester/target/scala-2.12/IntegTester-assembly-1.0.jar &
      - sbt installEquella startEquella
      - sbt configureInstall setupForTests ${OTHER_TESTS} Tests/test
      - sbt coverageReport
  post_build:
    commands:
      - sbt collectArtifacts
artifacts:
  files:
    - target/test-artifacts.zip
  discard-paths: yes
