name: openEQUELLA CI

on: [push]

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: SBT Cache
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Ivy Cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-ivy-

      - name: Set up NVM
        shell: bash -l -eo pipefail {0}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          echo "source $NVM_DIR/nvm.sh" >> "$HOME/.bash_profile"

      - name: Install NodeJS
        shell: bash -l -eo pipefail {0}
        run: |
          nvm install

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install node dependencies (core)
        shell: bash -l -eo pipefail {0}
        working-directory: Source/Plugins/Core/com.equella.core/js 
        run: |
          npm ci

      - name: Install node dependencies (root)
        shell: bash -l -eo pipefail {0}
        run: |
          npm ci

      - name: Run checks
        shell: bash -l -eo pipefail {0}
        run: |
          npm run check
          ./sbt headerCheck checkJavaCodeStyle

      - name: Run unit tests (java/scala)
        shell: bash -l -eo pipefail {0}
        run: |
          ./sbt test

      - name: Run unit tests (javascript)
        shell: bash -l -eo pipefail {0}
        working-directory: Source/Plugins/Core/com.equella.core/js 
        run: |
          npm cit

      - name: Build primary artefacts
        shell: bash -l -eo pipefail {0}
        run: |
          ./sbt installerZip writeLanguagePack writeScriptingJavadoc

      - name: Package artefacts
        # We use --transform below to strip out the path for the files in the tar file
        run: |
          tar cvf artefacts.tar --transform='s/.\+\///' \
            Installer/target/equella-installer*.zip \
            Source/Server/equellaserver/target/tle-upgrade*.zip \
            target/*.zip

      - name: Save primary artefacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: Artefacts
          path: artefacts.tar
