name: openEQUELLA CI

on: [push]

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up NVM
        shell: bash -l {0}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

      - name: Install NodeJS
        shell: bash -l {0}
        run: |
          nvm install

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install node dependencies (core)
        shell: bash -l {0}
        run: |
          cd Source/Plugins/Core/com.equella.core/js && npm install-ci

      - name: Install node dependencies (root)
        shell: bash -l {0}
        run: |
          npm install-ci

      - name: Run checks
        shell: bash -l {0}
        run: |
          npm run check
          ./sbt headerCheck checkJavaCodeStyle

